kind: pipeline
name: default
type: docker

steps:
  - name: flake8
    image: python
    commands:
      - pip install flake8
      - flake8 pynyaata --ignore=E501
  - name: docker
    image: plugins/docker
    settings:
      repo: xefir/pynyaata
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: pypi
    image: plugins/pypi
    settings:
      username:
        from_secret: pypi_username
      password:
        from_secret: pypi_password
    when:
      branch:
        - master

---
kind: pipeline
name: dependabot
type: docker

steps:
  - name: dependabot
    image: xefir/docker-dependabot-gitea
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: github_access_token
      GITEA_ACCESS_TOKEN:
        from_secret: gitea_access_token
    when:
      event:
        - cron
