kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: xefir/pynyaata
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: pypi
    image: plugins/pypi
    settings:
      username:
        from_secret: pipy_username
      password:
        from_secret: pipy_password
