version: "2.4"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    entrypoint: python3 run.py
    working_dir: /app
    depends_on:
      - db
      - cloudproxy
    env_file:
      - .env.dist
      - .env
    volumes:
      - .:/app

  db:
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env.dist
      - .env
    volumes:
      - ./.db:/var/lib/mysql

  cloudproxy:
    image: jbouhd/cloudproxy
    ports:
      - "8191:8191"
    env_file:
      - .env.dist
      - .env
