version: "2.4"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    entrypoint: python3 app.py
    working_dir: /app
    env_file:
      - .env.dist
      - .env
    volumes:
      - .:/app

  db:
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env.dist
      - .env
    volumes:
      - ./.db:/var/lib/mysql
